//             item.Job_title = item.Job_title.Replace("\n", "");
//             item.Job_title = item.Job_title.Replace(":", "");
//             item.Job_title = item.Job_title.Replace(",", "");
//             item.Job_title = item.Job_title.Replace("/", "");
//             item.Job_title = item.Job_title.Replace(".", "");
//             item.Job_title = item.Job_title.Replace(".", "");
//             item.Job_title = item.Job_title.Replace("|", "");
//             item.Job_title = item.Job_title.Replace("\\", "");
//             item.Job_title = item.Job_title.Replace("<", "");
//             item.Job_title = item.Job_title.Replace(">", "");
//             item.Job_title = item.Job_title.Replace("$", "");
//             item.Job_title = item.Job_title.Replace("=", "");
//             item.Job_title = item.Job_title.Replace("+", "");
//             item.Job_title = item.Job_title.Replace("%", "");
//             item.Job_title = item.Job_title.Replace("!", "");
//             item.Job_title = item.Job_title.Replace("`", "");
//             item.Job_title = item.Job_title.Replace("&", "");
//             item.Job_title = item.Job_title.Replace("*", "");
//             item.Job_title = item.Job_title.Replace("'", "");
//             item.Job_title = item.Job_title.Replace("{", "");
//             item.Job_title = item.Job_title.Replace("}", "");
//             item.Job_title = item.Job_title.Replace("?", "");
//             item.Job_title = item.Job_title.Replace("\"", "");
//             item.Job_title = item.Job_title.Replace("@", "");
            
//             item.Location = item.Location.Replace("\n", "");
//             item.Location = item.Location.Replace(":", "");
//             item.Location = item.Location.Replace("/", "");
//             item.Location = item.Location.Replace(".", "");
//             item.Location = item.Location.Replace(".", "");
//             item.Location = item.Location.Replace("|", "");
//             item.Location = item.Location.Replace("\\", "");
//             item.Location = item.Location.Replace("<", "");
//             item.Location = item.Location.Replace(">", "");
//             item.Location = item.Location.Replace("$", "");
//             item.Location = item.Location.Replace("=", "");
//             item.Location = item.Location.Replace("+", "");
//             item.Location = item.Location.Replace("%", "");
//             item.Location = item.Location.Replace("!", "");
//             item.Location = item.Location.Replace("`", "");
//             item.Location = item.Location.Replace("&", "");
//             item.Location = item.Location.Replace("*", "");
//             item.Location = item.Location.Replace("'", "");
//             item.Location = item.Location.Replace("{", "");
//             item.Location = item.Location.Replace("}", "");
//             item.Location = item.Location.Replace("?", "");
//             item.Location = item.Location.Replace("\"", "");
//             item.Location = item.Location.Replace("@", "");

//             item.Company = item.Company.Replace("\n", "");
//             item.Company = item.Company.Replace(" ", "");
//             item.Company = item.Company.Replace(":", "");
//             item.Company = item.Company.Replace(",", "");
//             item.Company = item.Company.Replace("/", "");
//             item.Company = item.Company.Replace(".", "");
//             item.Company = item.Company.Replace(".", "");
//             item.Company = item.Company.Replace("|", "");
//             item.Company = item.Company.Replace("\\", "");
//             item.Company = item.Company.Replace("<", "");
//             item.Company = item.Company.Replace(">", "");
//             item.Company = item.Company.Replace("$", "");
//             item.Company = item.Company.Replace("=", "");
//             item.Company = item.Company.Replace("+", "");
//             item.Company = item.Company.Replace("%", "");
//             item.Company = item.Company.Replace("!", "");
//             item.Company = item.Company.Replace("`", "");
//             item.Company = item.Company.Replace("&", "");
//             item.Company = item.Company.Replace("*", "");
//             item.Company = item.Company.Replace("'", "");
//             item.Company = item.Company.Replace("{", "");
//             item.Company = item.Company.Replace("}", "");
//             item.Company = item.Company.Replace("?", "");
//             item.Company = item.Company.Replace("\"", "");
//             item.Company = item.Company.Replace("@", "");

//             item.Job_location = item.Job_location.Replace("\n", "");
//             item.Job_location = item.Job_location.Replace("  ", "");
//             item.Job_location = item.Job_location.Replace(":", "");
//             item.Job_location = item.Job_location.Replace(",", "");
//             item.Job_location = item.Job_location.Replace("/", "");
//             item.Job_location = item.Job_location.Replace(".", "");
//             item.Job_location = item.Job_location.Replace(".", "");
//             item.Job_location = item.Job_location.Replace("|", "");
//             item.Job_location = item.Job_location.Replace("\\", "");
//             item.Job_location = item.Job_location.Replace("<", "");
//             item.Job_location = item.Job_location.Replace(">", "");
//             item.Job_location = item.Job_location.Replace("$", "");
//             item.Job_location = item.Job_location.Replace("=", "");
//             item.Job_location = item.Job_location.Replace("+", "");
//             item.Job_location = item.Job_location.Replace("%", "");
//             item.Job_location = item.Job_location.Replace("!", "");
//             item.Job_location = item.Job_location.Replace("`", "");
//             item.Job_location = item.Job_location.Replace("&", "");
//             item.Job_location = item.Job_location.Replace("*", "");
//             item.Job_location = item.Job_location.Replace("'", "");
//             item.Job_location = item.Job_location.Replace("{", "");
//             item.Job_location = item.Job_location.Replace("}", "");
//             item.Job_location = item.Job_location.Replace("?", "");
//             item.Job_location = item.Job_location.Replace("\"", "");
//             item.Job_location = item.Job_location.Replace("@", "");

//             item.Seniority_level = item.Seniority_level.Replace("\n", "");
//             item.Seniority_level = item.Seniority_level.Replace("  ", "");
//             item.Seniority_level = item.Seniority_level.Replace(":", "");
//             item.Seniority_level = item.Seniority_level.Replace(",", "");
//             item.Seniority_level = item.Seniority_level.Replace("/", "");
//             item.Seniority_level = item.Seniority_level.Replace(".", "");
//             item.Seniority_level = item.Seniority_level.Replace(".", "");
//             item.Seniority_level = item.Seniority_level.Replace("|", "");
//             item.Seniority_level = item.Seniority_level.Replace("\\", "");
//             item.Seniority_level = item.Seniority_level.Replace("<", "");
//             item.Seniority_level = item.Seniority_level.Replace(">", "");
//             item.Seniority_level = item.Seniority_level.Replace("$", "");
//             item.Seniority_level = item.Seniority_level.Replace("=", "");
//             item.Seniority_level = item.Seniority_level.Replace("+", "");
//             item.Seniority_level = item.Seniority_level.Replace("%", "");
//             item.Seniority_level = item.Seniority_level.Replace("!", "");
//             item.Seniority_level = item.Seniority_level.Replace("`", "");
//             item.Seniority_level = item.Seniority_level.Replace("&", "");
//             item.Seniority_level = item.Seniority_level.Replace("*", "");
//             item.Seniority_level = item.Seniority_level.Replace("'", "");
//             item.Seniority_level = item.Seniority_level.Replace("{", "");
//             item.Seniority_level = item.Seniority_level.Replace("}", "");
//             item.Seniority_level = item.Seniority_level.Replace("?", "");
//             item.Seniority_level = item.Seniority_level.Replace("\"", "");
//             item.Seniority_level = item.Seniority_level.Replace("@", "");

//             item.Job_function = item.Job_function.Replace("\n", "");
//             item.Job_function = item.Job_function.Replace("  ", "");
//             item.Job_function = item.Job_function.Replace(":", "");
//             item.Job_function = item.Job_function.Replace(",", "");
//             item.Job_function = item.Job_function.Replace("/", "");
//             item.Job_function = item.Job_function.Replace(".", "");
//             item.Job_function = item.Job_function.Replace(".", "");
//             item.Job_function = item.Job_function.Replace("|", "");
//             item.Job_function = item.Job_function.Replace("\\", "");
//             item.Job_function = item.Job_function.Replace("<", "");
//             item.Job_function = item.Job_function.Replace(">", "");
//             item.Job_function = item.Job_function.Replace("$", "");
//             item.Job_function = item.Job_function.Replace("=", "");
//             item.Job_function = item.Job_function.Replace("+", "");
//             item.Job_function = item.Job_function.Replace("%", "");
//             item.Job_function = item.Job_function.Replace("!", "");
//             item.Job_function = item.Job_function.Replace("`", "");
//             item.Job_function = item.Job_function.Replace("&", "");
//             item.Job_function = item.Job_function.Replace("*", "");
//             item.Job_function = item.Job_function.Replace("'", "");
//             item.Job_function = item.Job_function.Replace("{", "");
//             item.Job_function = item.Job_function.Replace("}", "");
//             item.Job_function = item.Job_function.Replace("?", "");
//             item.Job_function = item.Job_function.Replace("\"", "");
//             item.Job_function = item.Job_function.Replace("@", "");

//             item.Industries = item.Industries.Replace("\n", "");
//             item.Industries = item.Industries.Replace("  ", "");
//             item.Industries = item.Industries.Replace(":", "");
//             item.Industries = item.Industries.Replace("/", "");
//             item.Industries = item.Industries.Replace(".", "");
//             item.Industries = item.Industries.Replace(".", "");
//             item.Industries = item.Industries.Replace("|", "");
//             item.Industries = item.Industries.Replace("\\", "");
//             item.Industries = item.Industries.Replace("<", "");
//             item.Industries = item.Industries.Replace(">", "");
//             item.Industries = item.Industries.Replace("$", "");
//             item.Industries = item.Industries.Replace("=", "");
//             item.Industries = item.Industries.Replace("+", "");
//             item.Industries = item.Industries.Replace("%", "");
//             item.Industries = item.Industries.Replace("!", "");
//             item.Industries = item.Industries.Replace("`", "");
//             item.Industries = item.Industries.Replace("&", "");
//             item.Industries = item.Industries.Replace("*", "");
//             item.Industries = item.Industries.Replace("'", "");
//             item.Industries = item.Industries.Replace("{", "");
//             item.Industries = item.Industries.Replace("}", "");
//             item.Industries = item.Industries.Replace("?", "");
//             item.Industries = item.Industries.Replace("\"", "");
//             item.Industries = item.Industries.Replace("@", "");


//             item.Job_description = item.Job_description.Replace("\n", "");
//             item.Job_description = item.Job_description.Replace("  ", "");
//             // item.Job_description = item.Job_description.Replace(":", "");
//             // item.Job_description = item.Job_description.Replace(",", "");
//             // item.Job_description = item.Job_description.Replace("/", "");
//             // item.Job_description = item.Job_description.Replace(".", "");
//             // item.Job_description = item.Job_description.Replace(".", "");
//             // item.Job_description = item.Job_description.Replace("|", "");
//             // item.Job_description = item.Job_description.Replace("\\", "");
//             // item.Job_description = item.Job_description.Replace("<", "");
//             // item.Job_description = item.Job_description.Replace(">", "");
//             // item.Job_description = item.Job_description.Replace("$", "");
//             // item.Job_description = item.Job_description.Replace("=", "");
//             // item.Job_description = item.Job_description.Replace("+", "");
//             // item.Job_description = item.Job_description.Replace("%", "");
//             // item.Job_description = item.Job_description.Replace("!", "");
//             // item.Job_description = item.Job_description.Replace("`", "");
//             // item.Job_description = item.Job_description.Replace("&", "");
//             // item.Job_description = item.Job_description.Replace("*", "");
//             // item.Job_description = item.Job_description.Replace("'", "");
//             // item.Job_description = item.Job_description.Replace("{", "");
//             // item.Job_description = item.Job_description.Replace("}", "");
//             // item.Job_description = item.Job_description.Replace("?", "");
//             // item.Job_description = item.Job_description.Replace("\"", "");
//             // item.Job_description = item.Job_description.Replace("@", "");
            

//         }
//         string modifiedJson = JsonConvert.SerializeObject(jobItems, Formatting.Indented);

//         // Console.WriteLine("Original JSON:");
//         // Console.WriteLine(json);

//         Console.WriteLine("\nModified JSON:");
//         Console.WriteLine(modifiedJson);
//         string
//         outputFile = "modified_JobData.json"        ;
//         File.WriteAllText(outputFile, modifiedJson);

//         Console.WriteLine($"\nModified JSON data saved to: {outputFile}");